name: Build

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get dependencies and build
      run: |
        yarn install
        yarn build
    - name: SCP Command to Transfer Files
      # You may pin to the exact commit or the version.
      # uses: appleboy/scp-action@8a92fcdb1eb4ffbf538b2fa286739760aac8a95b
      uses: appleboy/scp-action@v0.1.4
      with:
        # scp remote host
        host: ${{ secrets.HOST }}
        # scp username
        username: ${{ secrets.USER }}
        # scp password
        password: ${{ secrets.PWD }}
        # target path on the server, must be a directory path.
        target: /deploy/sub-web
        # scp file list
        source: dist/index.html
        # remove target folder before upload data
        rm: true
